[settings]
experimental = true
pipx_uvx = true
lockfile = true
[tools]
ghq = "1.8.0"
node = "24"
go = "1.25.4"
terraform = "1.12.2"
jq = "1.8.1"
deno = "2.4.3"
bun = "1.3.3"
neovim = "0.11.3"
lua = "5.1"
ripgrep = "14.1.1"
fd = "10.2.0"
"aqua:opentofu/opentofu" = "1.11.2"
"aqua:1password/cli" = "2.32.0"
"npm:@anthropic-ai/claude-code" = "2.0.73"
"aqua:aws/session-manager-plugin"="1.2.707.0"
"aqua:direnv/direnv" = "v2.37.1"
"npm:@openai/codex" = "latest"
"aqua:slack.com/slack-cli" = "3.5.2"
"aqua:suzuki-shunsuke/tfmv" = "0.2.8"
"aqua:aws/aws-sam-cli" = "1.151.0"
"pipx:datadog" = "latest"
"npm:kzdiff" = "1.6.1"
"npm:safe-command" = "latest"
"npm:@github/copilot" = "0.0.353"
"npm:opencommit" = "3.2.10"
"npm:@devcontainers/cli" = "0.80.1"
"npm:@modelcontextprotocol/server-memory" = "2025.11.25"
"npm:ccstatusline" = "2.0.23"
"npm:wrangler" = "4.45.3"
"npm:renovate" = "latest"
"aqua:suzuki-shunsuke/pinact" = "3.4.2"
"go:github.com/aquaproj/aqua/v2/cmd/aqua" = "2.55.1"
"go:github.com/syumai/sbx/cmd/sbx" = "0.0.5"
"go:github.com/dagger/container-use/cmd/container-use" = "0.4.2"
"checkov" = "3.2.489"
"aqua:astral-sh/uv" = "0.9.7"
"aqua:junegunn/fzf" = "0.66.1"
"aqua:homeport/dyff" = "1.10.2"
"aqua:cli/cli" = "2.82.1"
"aqua:aws/aws-cli" = "2.31.27"
# MCP servers
"pipx:awslabs.aws-documentation-mcp-server" = "1.1.9"
"pipx:awslabs.aws-pricing-mcp-server" = "1.0.16"
#nvim
"npm:neovim" = "5.4.0"
"aqua:tree-sitter/tree-sitter" = "0.25.10"
biome = "2.3.7"
[tasks.mise_setup]
description = "Setup mise tools"
run = "bun run karabiner/karabiner.ts"

[tool_alias]
tf = "tofu"

